### ISSUE TITLE
Question regarding launching AMI chiron

### ISSUE THREAD

**Issue by misic** [IGS/Chiron#27]
Hello - I attended the IGS workshop in Baltimore in June 2017. Thank you very much, I found the workshop very useful. I'm trying to set up a new ami but cannot find chiron anymore in the public images. Is it gone? Do you have other suggestions on how to launch this AMI?

Thanks!
Ana

**Comment by victor73** [comment]
Hello Ana,

It is not gone. How are you doing the search? Are you certain you searched ALL AMIs and not just your own AMIs? The AMI ID for Chiron is:  ami-21530437

**Comment by misic** [comment]
Hi Victor - Thank you, I just found it when I changed my location to N. Virginia. I did not find it when I was searching under the location US East (Ohio). I'm not sure why that is.
Thanks for your fast response!
Ana

**Comment by adkinsrs** [comment]
Hi Ana,

AMI's are typically tied to a specific region, if I understand correctly, since each region's EC2 resources are isolated from the other regions.  To run the Chiron image under the US East - Ohio region, for example, a whole new AMI would have to be created.

**Comment by victor73** [comment]
More information on that topic here:

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/CopyingAMIs.html
